name: Sample WF
# manual trigger
on: workflow_dispatch
jobs: 
  # this wf coontains a single job
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: ls -althr
      - name: print goodbye
        run: echo "Done - bye!"
